const $=id=>document.getElementById(id);let catalog=null,current=null,rows={};
const defs=[
{id:'execPlan',stage:'啟動',name:'執行服務計畫書',base:'sign',days:30,pcm:true,basis:'簽約後30日內提送'},
{id:'surveyPlan',stage:'調查',name:'補充測量工作計畫書',base:'sign',days:30,pcm:true,basis:'簽約後30日內提送'},
{id:'geoPlan',stage:'調查',name:'補充地質調查工作計畫書',base:'sign',days:30,pcm:true,basis:'簽約後30日內提送'},
{id:'utilityPlan',stage:'調查',name:'管線調查工作計畫書',base:'sign',days:30,pcm:true,basis:'簽約後30日內提送'},
{id:'surveyResult',stage:'調查',name:'補充測量成果報告',base:'surveyPlanApproval',days:120,pcm:true,basis:'工作計畫核定後120日內'},
{id:'geoResult',stage:'調查',name:'補充地質調查成果報告',base:'geoPlanApproval',days:120,pcm:true,basis:'工作計畫核定後120日內'},
{id:'utilityResult',stage:'調查',name:'管線調查成果報告',base:'utilityPlanApproval',days:120,pcm:true,basis:'工作計畫核定後120日內'},
{id:'basic',stage:'設計',name:'基本設計成果初稿',base:'execPlanApproval',days:150,pcm:true,basis:'執行服務計畫書核定後150日內'},
{id:'final',stage:'設計',name:'期末設計成果初稿',base:'finalBase',days:300,pcm:true,basis:'基本設計核定後（或通知日起）300日內'}];
function parse(s){if(!s)return null;const d=new Date(s+'T12:00:00');return isNaN(d)?null:d}function iso(d){return d?d.toISOString().slice(0,10):''}function fmt(d){return d?iso(d).replaceAll('-','/'):''}function addDays(d,n){if(!d)return null;let x=new Date(d);x.setDate(x.getDate()+Number(n||0));return x}function money(n){return Number(n||0).toLocaleString('zh-TW',{maximumFractionDigits:0})}function pct(n){return (Math.round(n*100)/100).toFixed(2)+'%'}
function holidays(){return new Set(($('holidays').value||'').split(/[\s,;]+/).filter(Boolean))}function addWorkdays(d,n){if(!d)return null;let x=new Date(d),c=0,h=holidays();while(c<Number(n||0)){x.setDate(x.getDate()+1);let day=x.getDay(),s=iso(x);if(day!==0&&day!==6&&!h.has(s))c++;}return x}
function localKey(){return 'yilan-dashboard-'+current.id}
async function init(){catalog=await fetch('projects.json',{cache:'no-store'}).then(r=>r.json());$('projectSelect').innerHTML=catalog.projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('segmentButtons').innerHTML=catalog.projects.map(p=>`<button class="segment-btn" data-project="${p.id}" onclick="switchProject('${p.id}')">${p.name}</button>`).join('');const q=new URLSearchParams(location.search);const last=localStorage.getItem('yilan-dashboard-last-project');await loadProject(last||catalog.defaultProject);if(q.get('view')==='1')toggleViewMode(true)}
async function loadProject(id){const p=catalog.projects.find(x=>x.id===id)||catalog.projects[0];current=await fetch(p.data,{cache:'no-store'}).then(r=>r.json());const local=localStorage.getItem(localKey());if(local){try{current=JSON.parse(local)}catch(e){}}rows={...(current.rows||{})};$('projectSelect').value=current.id;localStorage.setItem('yilan-dashboard-last-project',current.id);document.querySelectorAll('.segment-btn').forEach(b=>b.classList.toggle('active',b.dataset.project===current.id));hydrate();recalc()}
function hydrate(){ $('heroSub').textContent=current.title; $('heroTitle').textContent='宜蘭至羅東鐵路高架化計畫｜'+current.name+'履約＋付款管制'; const m=current.milestones||{};$('awardDate').value=m.awardDate||'';$('evaluationDate').value=m.evaluationDate||'';$('negotiationDate').value=m.negotiationDate||'';$('signDate').value=m.signDate||'';$('pcmDays').value=current.settings?.pcmDays??30;$('payMode').value=String(current.settings?.payWorkdays??30);$('forecastMode').value=current.settings?.forecastMode||'budget';$('holidays').value=(current.settings?.holidays||[]).join(', ');for(const k of ['noticeDate','pccDate','tenderApprovalDate','allWorksAwardDate','allWorksCloseDate','supervisionStart','constructionStart','constructionEnd','constructionClose'])$(k).value=current.dates?.[k]||'';renderBadges();renderBudget()}
function renderBadges(){const m=current.milestones||{};let a=[];if(m.awardDate)a.push('決標 '+m.awardDate.replaceAll('-','/'));if(m.evaluationDate)a.push('評選 '+m.evaluationDate.replaceAll('-','/'));if(m.negotiationDate)a.push('議價 '+m.negotiationDate.replaceAll('-','/'));if(m.signDate)a.push('簽約 '+m.signDate.replaceAll('-','/'));$('badges').innerHTML=a.map(x=>`<span class="badge">${x}</span>`).join('')+`<span class="badge">共用程式 / JSON資料</span>`}
function renderBudget(){const labels={survey:['補充測量','實作數量結算'],geo:['補充地質調查','實作數量結算'],utility:['管線調查','實作數量結算'],land:['用地及地上物相關作業','依契約/實作'],design:['工程設計','付款里程碑'],supervision:['施工監造','進駐款＋工程進度估驗']};$('budgetNote').innerHTML=`${current.name}預算總額 <b>${money(current.budget.total)} 元</b>；發包技術服務費 <b>${money(current.budget.serviceTotal)} 元</b>。${current.notes||''}`;$('budgetTable').querySelector('tbody').innerHTML=Object.entries(labels).map(([k,v])=>`<tr><td>${v[0]}</td><td class="num">${money(current.budget[k])}</td><td><input class="contractAmt" data-key="${k}" type="number" value="${current.contract?.[k]??current.budget[k]}"></td><td class="num usedAmt" data-key="${k}"></td><td>${v[1]}</td></tr>`).join('')}
function used(k){return $('forecastMode').value==='budget'?Number(current.budget[k]||0):Number(document.querySelector(`.contractAmt[data-key="${k}"]`)?.value||0)}
function actualField(id,kind){const key=id+'_'+kind;return `<input type="date" value="${rows[key]||''}" onchange="rows['${key}']=this.value;recalc()">`}function actual(id,k){return parse(rows[id+'_'+k]||'')}function eventDate(id,k,fallback){return actual(id,k)||fallback}
function baseDate(def,c){if(def.base==='sign')return parse($('signDate').value);if(def.base==='execPlanApproval')return c.execPlanApproval;if(def.base==='surveyPlanApproval')return c.surveyPlanApproval;if(def.base==='geoPlanApproval')return c.geoPlanApproval;if(def.base==='utilityPlanApproval')return c.utilityPlanApproval;if(def.base==='finalBase')return parse($('noticeDate').value)||c.basicApproval;return null}
function status(deadline,act){if(!deadline)return '<span class="pill p-orange">待基準日</span>';if(act)return act<=deadline?'<span class="pill p-green">已提送 / 未逾期</span>':'<span class="pill p-red">實際逾期</span>';let t=new Date();t.setHours(12,0,0,0);if(t>deadline)return '<span class="pill p-red">已逾期未登錄</span>';let diff=Math.ceil((deadline-t)/86400000);return diff<=14?`<span class="pill p-orange">${diff}日內到期</span>`:'<span class="pill p-blue">管制中</span>'}
function computeSchedule(){let c={},pcm=Number($('pcmDays').value||0),html='';for(const d of defs){let b=baseDate(d,c),deadline=addDays(b,d.days),act=actual(d.id,'submit'),approvalFallback=addDays(act||deadline,pcm),approval=eventDate(d.id,'approval',approvalFallback);c[d.id+'Deadline']=deadline;c[d.id+'Submit']=act||deadline;c[d.id+'Approval']=approval;let baseName=d.base==='sign'?'簽約日':d.base==='execPlanApproval'?'執行服務計畫核定日':d.base==='surveyPlanApproval'?'測量工作計畫核定日':d.base==='geoPlanApproval'?'地質工作計畫核定日':d.base==='utilityPlanApproval'?'管線工作計畫核定日':'基本設計核定日 / 甲方通知日';html+=`<tr><td class="center"><span class="pill p-blue">${d.stage}</span></td><td>${d.name}</td><td>${baseName}<br><span class="small">${fmt(b)}</span></td><td class="center">${d.days}日</td><td class="center"><b>${fmt(deadline)||'-'}</b></td><td>${actualField(d.id,'submit')}</td><td>${actualField(d.id,'approval')}<div class="small">預估：${fmt(approvalFallback)||'-'}</div></td><td class="center">${status(deadline,act)}</td><td>${d.basis}<br><span class="small">未填核定日：以提送/期限＋PCM管理預估${pcm}日</span></td></tr>`} $('scheduleTable').querySelector('tbody').innerHTML=html;return c}
function payDate(d){return addWorkdays(d,Number($('payMode').value||0))}
function computePayments(c){const design=used('design'),pay=[];let cum=0;const add=(cat,name,ratio,trigger,note,isDesign=false)=>{if(isDesign)cum+=ratio;let base=cat==='工程設計'?design:cat==='補充測量'?used('survey'):cat==='補充地質'?used('geo'):cat==='管線調查'?used('utility'):0;pay.push({cat,name,ratio,trigger,pay:payDate(trigger),amt:base*ratio/100,cum:isDesign?cum:null,note})};add('工程設計','契約簽訂',10,parse($('signDate').value),'簽約完成',true);add('補充測量','工作計畫書經甲方同意',10,c.surveyPlanApproval,'先付10%');add('補充地質','工作計畫書經甲方同意',10,c.geoPlanApproval,'先付10%');add('管線調查','工作計畫書經甲方同意',10,c.utilityPlanApproval,'先付10%');add('工程設計','執行服務計畫書經甲方同意',10,c.execPlanApproval,'設計累計20%',true);add('補充測量','正式成果核可／實作結算',90,c.surveyResultApproval,'現金流以餘90%上限估算；實際依實作');add('補充地質','正式成果核可／實作結算',90,c.geoResultApproval,'現金流以餘90%上限估算；實際依實作');add('管線調查','正式成果核可／實作結算',90,c.utilityResultApproval,'現金流以餘90%上限估算；實際依實作');add('工程設計','基本設計成果審查核可',20,c.basicApproval,'設計累計40%',true);add('工程設計','計畫經費審議經工程會核定',5,parse($('pccDate').value),'日期未填則不列年度',true);add('工程設計','期末設計成果審查核可',40,c.finalApproval,'設計累計85%',true);add('工程設計','招標文件成果審查核可',5,parse($('tenderApprovalDate').value),'設計累計90%',true);add('工程設計','各分標工程決標完成',5,parse($('allWorksAwardDate').value),'依各標工程預算比例支付',true);add('工程設計','全部工程竣工驗收、結算且無待解決事項',5,parse($('allWorksCloseDate').value),'設計累計100%',true);let years={};$('paymentTable').querySelector('tbody').innerHTML=pay.map(x=>{let y=x.pay?x.pay.getFullYear():'';if(y){years[y]??={amt:0,count:0};years[y].amt+=x.amt;years[y].count++}return `<tr><td class="center">${x.cat}</td><td>${x.name}</td><td class="center">${pct(x.ratio)}</td><td class="center">${fmt(x.trigger)||'-'}</td><td class="center"><b>${fmt(x.pay)||'-'}</b></td><td class="num">${money(x.amt)}</td><td class="center">${x.cum!==null?pct(x.cum):'-'}</td><td class="center">${y||'-'}</td><td>${x.note}</td></tr>`}).join('');let ys=Object.keys(years).sort();$('yearSummary').querySelector('tbody').innerHTML=ys.length?ys.map(y=>`<tr><td>${y}（民國${Number(y)-1911}年）</td><td class="right"><b>${money(years[y].amt)}</b></td><td class="right">${years[y].count}</td></tr>`).join(''):'<tr><td colspan="3" class="small">目前沒有可推估付款日之資料</td></tr>'}
function computeSupervision(){let total=used('supervision'),start=parse($('supervisionStart').value),cs=parse($('constructionStart').value),ce=parse($('constructionEnd').value),close=parse($('constructionClose').value),arr=[],cum=0;if(start){cum=5;arr.push({n:'進駐款',period:'監造計畫核定＋人員進駐',ratio:5,trigger:start,cum,note:'契約固定條件'})}if(cs&&ce&&ce>cs){let pts=[],cur=new Date(cs);while(cur<ce){let n=new Date(cur);n.setMonth(n.getMonth()+2);if(n>ce)n=new Date(ce);pts.push(n);cur=n}let r=93/pts.length;pts.forEach((d,i)=>{cum+=r;arr.push({n:'估驗'+(i+1),period:'每2個月線性模擬',ratio:r,trigger:d,cum,note:'管理模擬；實際依施工進度'})})}if(close)arr.push({n:'尾款',period:'竣工驗收＋結算＋無待解決事項',ratio:2,trigger:close,cum:100,note:'契約尾款2%'});$('supervisionTable').querySelector('tbody').innerHTML=arr.length?arr.map(x=>`<tr><td class="center">${x.n}</td><td>${x.period}</td><td class="center">${pct(x.ratio)}</td><td class="center">${fmt(x.trigger)}</td><td class="center"><b>${fmt(payDate(x.trigger))}</b></td><td class="num">${money(total*x.ratio/100)}</td><td class="center">${pct(x.cum)}</td><td>${x.note}</td></tr>`).join(''):'<tr><td colspan="8" class="small">尚未輸入監造進駐 / 施工期程。</td></tr>'}
function updateUsed(){document.querySelectorAll('.usedAmt').forEach(td=>td.textContent=money(used(td.dataset.key)))}
window.recalc=function(){updateUsed();const c=computeSchedule();computePayments(c);computeSupervision()}
function collect(){current.milestones={awardDate:$('awardDate').value,evaluationDate:$('evaluationDate').value,negotiationDate:$('negotiationDate').value,signDate:$('signDate').value};current.settings={pcmDays:Number($('pcmDays').value||30),payWorkdays:Number($('payMode').value||30),forecastMode:$('forecastMode').value,holidays:($('holidays').value||'').split(/[\s,;]+/).filter(Boolean)};current.dates={};for(const k of ['noticeDate','pccDate','tenderApprovalDate','allWorksAwardDate','allWorksCloseDate','supervisionStart','constructionStart','constructionEnd','constructionClose'])current.dates[k]=$(k).value;current.contract={...current.contract};document.querySelectorAll('.contractAmt').forEach(e=>current.contract[e.dataset.key]=Number(e.value||0));current.rows={...rows};return current}
window.saveLocal=function(){localStorage.setItem(localKey(),JSON.stringify(collect()));alert('已儲存在此瀏覽器。')};window.resetLocal=function(){if(confirm('確定放棄本機修改並重新讀取 GitHub JSON？')){localStorage.removeItem(localKey());location.reload()}}
window.exportProjectJSON=function(){const blob=new Blob([JSON.stringify(collect(),null,2)],{type:'application/json;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=current.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.importProjectJSON=function(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const f=i.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{current=JSON.parse(r.result);rows={...(current.rows||{})};hydrate();recalc();saveLocal()}catch(e){alert('JSON 格式錯誤')}};r.readAsText(f,'utf-8')};i.click()}
window.exportExcel=function(){recalc();let tabs=[['履約主時程',$('scheduleTable')],['付款預測',$('paymentTable')],['年度資金需求',$('yearSummary')],['施工監造模擬',$('supervisionTable')]],html='<html><head><meta charset="utf-8"></head><body>';tabs.forEach(([n,t])=>html+='<h2>'+n+'</h2>'+t.outerHTML+'<br>');html+='</body></html>';let blob=new Blob(['\ufeff',html],{type:'application/vnd.ms-excel'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='宜蘭高架_'+current.name+'_履約付款管制_'+new Date().toISOString().slice(0,10)+'.xls';a.click()}
window.toggleViewMode=function(force){let on=typeof force==='boolean'?force:!document.body.classList.contains('view-mode');document.body.classList.toggle('view-mode',on);let q=new URLSearchParams(location.search);on?q.set('view','1'):q.delete('view');history.replaceState(null,'',location.pathname+(q.toString()?'?'+q.toString():''))}
window.switchProject=id=>loadProject(id);init().catch(e=>{document.body.innerHTML='<div style="padding:30px;font-family:sans-serif"><h2>無法載入資料</h2><p>此程式需透過 GitHub Pages 或本機 HTTP Server 執行，不能直接以 file:// 開啟。</p><pre>'+String(e)+'</pre></div>'});
